### ISSUE TITLE
Using as Gulp plugin throws TypeError and packing error

### ISSUE THREAD

**Issue by pnobbe** [krasimir/techy#37]
Hi,

I'm not sure if the following error is related to Techy or if my implementation is faulty, but I've been unable to resolve the following issue on my own. If you need more info or require more info about my implementation please message me back. If necessary I'll add you as a contributor to my project so you can look at the source code.

The error:
```
TypeError: cb is not a function
    at Object.compileCSS (E:\Git\fsv-csi\node_modules\techy\lib\index.js:232:5)
    at E:\Git\fsv-csi\node_modules\techy\lib\index.js:301:12
    at Gulp.gulp.task (E:\Git\fsv-csi\gulpfile.js:179:15)
    at module.exports (E:\Git\fsv-csi\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (E:\Git\fsv-csi\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (E:\Git\fsv-csi\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (E:\Git\fsv-csi\node_modules\orchestrator\index.js:134:8)
    at E:\Git\fsv-csi\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
Error packing Error: Techy: I can't copy E:\Git\fsv-csi\bin folder!
    at E:\Git\fsv-csi\node_modules\techy\lib\index.js:154:18
    at cb (E:\Git\fsv-csi\node_modules\ncp\lib\ncp.js:224:23)
    at onError (E:\Git\fsv-csi\node_modules\ncp\lib\ncp.js:216:12)
    at E:\Git\fsv-csi\node_modules\ncp\lib\ncp.js:134:16
    at FSReqWrap.oncomplete (fs.js:114:15)
```

The Gulp implementation:

```javascript
techy = require('techy').gulp(); // For databaseless blogging.

/**
 * Compile all blogs from Markdown to HTML.
 */
gulp.task('blog', () => {
    const blogSrcPath = CONFIG.SOURCE_ROOT + "/" + CONFIG.BLOG_DIR_NAME + '/articles/**/*.md';
    const blogDestPath = CONFIG.DEST_ROOT + '/' + CONFIG.BLOG_DIR_NAME;

    gulp.src(blogSrcPath)
        .pipe(techy())
        .pipe(gulp.dest(blogDestPath));
});

...
gulp.watch(CONFIG.SOURCE_ROOT + "/**/*.md", ['blog']);  // Watch and compile Markdown blog
...
```

**Comment by krasimir** [comment]
@pnobbe just released a new version. Can you please try with `1.2.5`.

**Comment by pnobbe** [comment]
@krasimir This seems to have fixed the TypeError and it now successfully generates HTML files from my Markdown files. Thanks for the quick response!

However, I am still getting the same packing error.

```
Error packing Error: Techy: I can't copy E:\Git\fsv-csi\bin folder!
    at E:\Git\fsv-csi\node_modules\techy\lib\index.js:154:18
    at cb (E:\Git\fsv-csi\node_modules\ncp\lib\ncp.js:224:23)
    at onError (E:\Git\fsv-csi\node_modules\ncp\lib\ncp.js:216:12)
    at E:\Git\fsv-csi\node_modules\ncp\lib\ncp.js:134:16
    at FSReqWrap.oncomplete (fs.js:114:15)
```

**Comment by krasimir** [comment]
Hm ... can you check what are the permissions for that folder. Techy uses ncp for copying stuff so it shouldn't have problems.

**Comment by pnobbe** [comment]
I'm using Windows, so it really couldn't be a permissions issue. 

Out of curiosity, what does Techy need to copy the `./bin` folder for?

**Comment by krasimir** [comment]
Techy has the concept for themes and every theme may have static files. Because Techy has no idea what needs to copy and what not simply tries to copy everything into the destination folder.

**Comment by pnobbe** [comment]
Can this be worked around by specifying a specific theme folder in the master config?

By the way, the error does not seem to pack any breaking consequences with it. The Markdown files still get processed into HTML files as usual.

**Comment by krasimir** [comment]
By the way is the gulp file in that `bin` folder?

**Comment by pnobbe** [comment]
No, this is my current folder structure:
![img](https://puu.sh/x968A/fe0cfa6d7a.png)

The .md files are under /src/blog and are copied into /public/blog/articles after running Techy.

`./bin` just contains my `www` file to start my Node server.

**Comment by krasimir** [comment]
Can you please try initializing the gulp plugin with a `dest` prop like so:
```
techy = require('techy').gulp({
  src: '/src/blog',
  dest: '/public/blog/articles'
});
```

**Comment by pnobbe** [comment]
@krasimir That seems to have solved the error message. I'm not noticing any negative behaviour when initializing it like that so I'll assume this fixed the issue.

Thanks!
