### ISSUE TITLE
Techy not working

### ISSUE THREAD

**Issue by ghost** [krasimir/techy#40]
I use techy for a college website and generate the site every day. It suddenly stopped working. I tried it in a more reliable dev environment, and the same problem happened. It hangs and none of the folders generate. This comes from a setup where it has been used for years. Suddenly, it's broken. The last successfully generation was in late April. Any idea?

Nevermind. There was an issue that actually has nothing to do with Techy. There was 17mb worth of base64 encoded media on a page, so Techy was taking nightmarishly long to process that file.

**CLOSED**

**Comment by BarryMode** [comment]
Nevermind. There was an issue that actually has nothing to do with Techy. There was 17mb worth of base64 encoded media on a page, so Techy was taking nightmarishly long to process that file. Meh, co-workers — am I right?

*CLOSED*
